### ISSUE TITLE
chore(ci/cd): automate test and deploy process

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/zalando.github.io-dev#76]
**As** software maintainer
**I Want** to Automate test and deploy process 
**So That** I simplify the  maintenance  of the software and assure reproducible deploys

## Tasks

- [ ] write smoke/e2e tests 
- [ ] make it run on travis-ci
- [ ] automate deployment when a PR is merged to master after smoke tests are passing

## Acceptance Criteria

- [ ] smoke test can be run locally and are integrated in the CI process
- [ ] a new version is deployed automatically after merge to master
